### ISSUE TITLE
Initialization for target domain model

### ISSUE THREAD

**Issue by KyominHwang** [Hongbin98/ProCA#5]
Hi!
First of all, thank you for your nice work!
While I read your paper and code in github, I have a question about initialization for target domain model.

I saw that the training process of other works in Unsupervised Domain Adaptation follows 1) Pre-train a model with source domain 2) Initialize target model with source domain pre-trained weight.

But in your code, it is hard to find Initialization step with source domain pre-trained weight.

Is there any initialization stage in the code, or am I mistaken?

**Comment by Hongbin98** [comment]
Thanks for your interest in our work~

In ProCA, it is both feasible to train the target model from scratch or initialize it with source domain pre-trained weight.

However, it would save more calculation costs if we initialize the target model with source domain pre-trained weight.  I will update this minor issue in the future.

**Comment by KyominHwang** [comment]
Thank you for your reply!
